plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.navigationdrawer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.navigationdrawer'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'com.google.android.material:material:1.12.0'
}
